#' Bind Rifttables by Row
#'
#' @description This function concatenates two or more rifttables horizontally,
#'   i.e., by row. In addition to \code{\link[dplyr]{bind_rows}}, it retains
#'   indentation attributes of the individual rifttables for printing via
#'   \code{\link[rifttable]{rt_gt}}.
#'
#' @param ... Tibbles generated by \code{\link[rifttable]{rifttable}}.
#'
#' @return Tibble, with indentations as attribute.
#' @export
rt_bind_rows <- function(...) {
  input_tbls <- list(...)
  result <- dplyr::bind_rows(input_tbls)
  indents <- tibble::tibble(
    inputs = list(...)) %>%
    dplyr::mutate(
      rows = purrr::map_dbl(
        .x = input_tbls,
        .f = nrow),
      cumrows_lag = dplyr::lag(
        cumsum(.data$rows),
        default = 0),
      indent2 = purrr::map(
        .x = .data$inputs,
        .f = ~attr(
          x = .x,
          which = "rt_gt.indent2")),
      indent4 = purrr::map(
        .x = .data$inputs,
        .f = ~attr(
          x = .x,
          which = "rt_gt.indent4")),
      indent2 = purrr::map2(
        .x = .data$indent2,
        .y = .data$cumrows_lag,
        .f = ~.x + .y),
      indent4 = purrr::map2(
        .x = .data$indent4,
        .y = .data$cumrows_lag,
        .f = ~.x + .y))
  attr(
    x = result,
    which = "rt_gt.indent2") <- purrr::flatten_int(indents$indent2)
  attr(
    x = result,
    which = "rt_gt.indent4") <- purrr::flatten_int(indents$indent4)
  result
}
